language: generic
sudo: true

addons:
  apt:
    packages:
      - xvfb

services:
  - docker

branches:
  only:
    - develop

env:
  - TEST_SUITE="runtime"
  - TEST_SUITE="pylint"
  - TEST_SUITE="jslint"
  - TEST_SUITE="csslint"

matrix:
  fast_finish: true
  allow_failures:
    env:
      - TEST_SUITE="pylint"
      - TEST_SUITE="jslint"
      - TEST_SUITE="csslint"

script:
  - ./travis/main.sh
