FROM deforce/lalka-chat-build-deps:latest

MAINTAINER CzT/DeForce <vlad@czt.lv>

ADD . /usr/lib/python2.7/site-packages/LalkaChat

RUN cd /usr/lib/python2.7/site-packages/LalkaChat                  && \
    mkdir -p ./conf                                                && \
    mv ./docker/stubs/cefpython3 /usr/lib/python2.7/site-packages/ && \
    mv ./docker/run /usr/local/bin/                                && \
    rm -rf ./docker                                                && \
    python ./setup.py build
CMD /usr/local/bin/run
