#!/bin/sh

webchatCF="/usr/lib/python2.7/site-packages/LalkaChat/conf/webchat.cfg"

if [ -f $webchatCF ];
then
   sed -i 's/^host =.*$/host = 0.0.0.0/' $webchatCF
   sed -i 's/^show_browser =.*$/show_browser = False/' $webchatCF
else
   printf '[server]\nhost = 0.0.0.0\nshow_browser = False\n' > $webchatCF
fi

cd /usr/lib/python2.7/site-packages/LalkaChat

python ./main.py
